config/routes.rb
Rails.application.routes.draw do
  resources :games

  root 'games#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game, only: [:create, :update, :show]

  def index
    @@games ||= {}
  end

  def create
    @game.join(params[:name])
    session[:player_name] = params[:name]

    redirect_to game_path(@game.name)
  end

  def update

    respond_to do |format|

      # if @game.players[0].to_s == session[:player_name]
      #   @game.play(session[:player_name], params[:x].to_i, params[:y].to_i,  'X')
      # else
      #   @game.play(session[:player_name], params[:x].to_i, params[:y].to_i, 'O')
      # end

      @game.play(session[:player_name], params[:x].to_i, params[:y].to_i, @game.players[0].to_s == session[:player_name] ? 'X' : 'O')

      format.html { redirect_to game_path(@game.name) }
      format.js


    end

  rescue Game::SpotTaken, Game::PlayOutOfTurn, Game::GameOver => e
    redirect_to game_path(@game.name), notice: e.class.to_s.demodulize.titleize
  end

  def show
  end

  private

  def set_game
    game_id = params[:id]
    @game = @@games[game_id] ||= Game.new(game_id)
  end

end

class Game
  SpotTaken = Class.new(StandardError)
  PlayOutOfTurn = Class.new(StandardError)
  GameOver = Class.new(StandardError)

  FirstPlayVal = 'X'

  attr_reader :players, :name, :data, :winner, :last_player

  def initialize(name)
    @name = name
    @players = []
    # @data = 3.times.map { 3.times.map { '' } }
    @data = Array.new(3) { Array.new(3) }
  end

  def join(player_name)
    players << player_name
  end

  def play(player_name, x, y, mark)
    raise GameOver if find_winner_play
    raise SpotTaken if data[x][y].present?
    raise PlayOutOfTurn if @last_player == player_name

    data[x][y] = mark.to_s.upcase #player_name
    @last_player = player_name

    # check if someone has won the game
    @winner = @last_player if find_winner_play
  end

  private

  def find_winner_play
    winning_combinations.each do |combination|
      #move to next array if array only contain nils
      next if combination.compact.empty?

      unique_tokens = combination.uniq

      return unique_tokens.first if unique_tokens.size == 1
      # return unique_tokens.size == 1
    end
    nil
  end

  def winning_combinations
    [
        data[0], data[1], data[2], # horizontal
        *3.times.map { |c| [data[0][c], data[1][c], data[2][c]] }, # vertical
        [data[0][0], data[1][1], data[2][2]], # diagonal left to right
        [data[0][2], data[1][1], data[2][0]] # diagonal right to left
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game_board.html.erb
<% count = 1 %>
<% game.data.each_with_index do |row, x| %>
    <% row.each_with_index do |value, y| %>
        <div style="float:left">
          <% if value.blank? %>
              <%= form_tag game_path(params[:id]), {class: 'form-horizontal', role: 'form', method: :put} do %>
                  <%= hidden_field_tag :x, x %>
                  <%= hidden_field_tag :y, y %>
                  <div class="well">
                    <div class="box">

                      <%= submit_tag 'play', :remote => true, :class => 'btn btn-default' %>
                    </div>
                  </div>
              <% end %>
          <% else %>
              <div class="well">
                <div class="box">
                  <h4><%= value %></h4>
                </div>
              </div>
          <% end %>
        </div>
        <% if  count % 3 == 0 %>
            <div style="clear:both"></div>
        <% end %>

        <% count += 1 %>
    <% end %>
<% end %>

app/views/games/index.html.erb
<%= form_tag(games_path, {class: 'form-horizontal', role: 'form', method: :post}) do %>

    <div class="form-group">
      <%= label_tag :name, nil, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-5">
        <%= text_field_tag :name, nil, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :game, nil, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-5">
        <%= text_field_tag :id, nil, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <!--<button type="submit" class="btn btn-default">Sign in</button>-->
        <%= submit_tag 'Join Game', :class => 'btn btn-primary' %>
      </div>
    </div>

<% end %>

app/views/games/show.html.erb
<% if  @game.winner %>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>Winner!</strong> <%= "The winner is: #{@game.winner}" %>
    </div>
<% end %>

<br/>


<div id="board">
  <%= render 'game_board', {:game => @game} %>
</div>




<div class="well well-sm">
  Game: <%= @game.name.titleize %>
  <br/>
  Players: <%= @game.players %>
</div>

<div style="clear:both"></div>
<br/>
<%= button_to 'Refresh', game_path(params[:id]), {:class => 'btn btn-primary', method: :get} %>

app/views/games/show.js.erb
$('#board').html("<%= escape_javascript (render 'game_board', {:game => @game}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TicTacToe" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TicTacToe</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New Game', games_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br/>
      <br/>
      <br/>
      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>